# Generated by Django 5.2.17 on 2026-09-01 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('involvement_type', models.CharField(choices=[('ACCUSED', 'Accused'), ('VICTIM', 'Victim'), ('WITNESS', 'Witness'), ('COMPLAINANT', 'Complainant'), ('SUSPECT', 'Suspect'), ('OTHER', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='cases.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='persons.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'person', 'involvement_type'), name='unique_case_person_involvement')],
            },
        ),
    ]
