# Generated by Django 5.2.17 on 2026-09-02 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_number', models.CharField(max_length=100)),
                ('evidence_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('collected_at', models.DateTimeField()),
                ('collection_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('IN_CUSTODY', 'In Custody'), ('SUBMITTED', 'Submitted'), ('ANALYZED', 'Analyzed'), ('RELEASED', 'Released'), ('DISPOSED', 'Disposed')], default='COLLECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='cases.case')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_evidence', to=settings.AUTH_USER_MODEL)),
                ('current_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodied_evidence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('COLLECTED', 'Collected'), ('TRANSFERRED', 'Transferred'), ('RECEIVED', 'Received'), ('SUBMITTED', 'Submitted'), ('RELEASED', 'Released')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('integrity_hash', models.CharField(blank=True, help_text='SHA-256 hash associated with the custody event.', max_length=64)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_transfers_out', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_transfers_in', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='documents.evidence')),
            ],
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('case', 'evidence_number'), name='unique_case_evidence_number'),
        ),
    ]
