# Generated by Django 5.2.17 on 2026-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_evidence_custodyevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
