# Generated by Django 5.2.17 on 2026-09-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentversion_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
