# Generated by Django 5.2.17 on 2026-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentversion_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='original_filename',
            field=models.CharField(max_length=255),
        ),
    ]
