# Generated by Django 5.2.17 on 2026-09-06 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentversion_original_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcessingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('extraction_method', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.PositiveIntegerField(null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('average_ocr_confidence', models.FloatField(null=True)),
                ('fir_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fir_date', models.CharField(blank=True, max_length=20, null=True)),
                ('fir_year', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('police_station', models.CharField(blank=True, max_length=100, null=True)),
                ('suspected_offence', models.TextField(blank=True, null=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_result', to='documents.documentversion')),
            ],
        ),
    ]
