# Generated by Django 5.2.17 on 2026-09-01 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('case_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('IN_COURT', 'In Court'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('police_station', models.CharField(blank=True, max_length=255)),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_role', models.CharField(choices=[('LEAD_INVESTIGATOR', 'Lead Investigator'), ('SUPPORTING_INVESTIGATOR', 'Supporting Investigator'), ('SUPERVISOR', 'Supervisor'), ('FORENSIC_OFFICER', 'Forensic Officer'), ('PROSECUTOR', 'Prosecutor'), ('COURT_STAFF', 'Court Staff'), ('JUDGE', 'Judge'), ('OBSERVER', 'Observer')], max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'user'), name='unique_case_member')],
            },
        ),
    ]
